export const SCHEDULING_CLIENT = 'SCHEDULING_CLIENT';
export const PROVIDER_PACKAGE = 'scheduling.provider';
export const APPOINTMENT_PACKAGE = 'scheduling.appointment';
export const SCHEDULE_OPTIONS_PACKAGE = 'scheduling.schedule_options';
export const SCHEDULING_SERVICE = 'SchedulingService';
export const PROVIDER_SERVICE = 'ProviderService';
export const SCHEDULE_OPTIONS_SERVICE = 'ScheduleOptionsService';
export * from './types/';
export * from './dtos/';
export * from './tokens/';
